import TopNav from "@/components/shared/top-nav";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

const euclidCircularB = localFont({
  src: [
    {
      path: "../public/fonts/Euclid Circular B Light.ttf",
      weight: "300",
      style: "normal"
    },
    {
      path: "../public/fonts/Euclid Circular B Light Italic.ttf",
      weight: "300",
      style: "italic"
    },
    {
      path: "../public/fonts/Euclid Circular B Regular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../public/fonts/Euclid Circular B Medium.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "../public/fonts/Euclid Circular B Medium Italic.ttf",
      weight: "500",
      style: "italic"
    },
    {
      path: "../public/fonts/Euclid Circular B SemiBold.ttf",
      weight: "600",
      style: "normal"
    },
    {
      path: "../public/fonts/Euclid Circular B SemiBold Italic.ttf",
      weight: "600",
      style: "italic"
    },
    {
      path: "../public/fonts/Euclid Circular B Bold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "../public/fonts/Euclid Circular B Bold Italic.ttf",
      weight: "700",
      style: "italic"
    }
  ],
  variable: "--font-euclid",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Myxellia",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${euclidCircularB.className} animate-in fade-in-0 antialiased duration-300`}
        suppressHydrationWarning
      >
        <TopNav />
        {children}
      </body>
    </html>
  );
}
